[
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190.jpg","/images/front/travel/vis-size/vis-240x190-2.jpg","/images/front/travel/vis-size/vis-240x190-3.jpg"],
    "thumbAlt": ["test", "test2", "test3"],
    "wish": true,
    "titleKr": "1레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 4,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "현재인기"],
    "price1": 3,
    "price2": 238700,
    "link": "http://www.nate.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-2.jpg"],
    "thumbAlt": ["test"],
    "wish": true,
    "titleKr": "2그린 톨토이즈 호스텔 시애틀 - 아메리카스 베스트 밸류 에어포트 인",
    "grade": "아주 좋음 4.5",
    "titleEn": "The Royal Pacific Hotel & Towers Americas Best Val ue Airport Inn -  Seatac, WA agoda Seatac, WA agoda",
    "gradeStar": 5,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["예약수 높음", "신규호텔"],
    "price1": 2,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "award",
    "titleAward": "2018 상반기 베스트 셀러 1위",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-3.jpg", "/images/front/travel/vis-size/vis-240x190-2.jpg"],
    "thumbAlt": ["test", "test2"],
    "wish": false,
    "titleKr": "3레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 3,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가1", "베스트셀러"],
    "price1": 3,
    "price2": 321700,
    "link": "http://google.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190.jpg", "/images/front/travel/vis-size/vis-240x190-3.jpg"],
    "thumbAlt": ["test", "test2"],
    "wish": false,
    "titleKr": "4레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 1,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-2.jpg"],
    "thumbAlt": ["test2"],
    "wish": true,
    "titleKr": "5레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 2,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-3.jpg"],
    "thumbAlt": ["test3"],
    "wish": true,
    "titleKr": "6레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 3,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190.jpg", "/images/front/travel/vis-size/vis-240x190-2.jpg"],
    "thumbAlt": ["test", "test2"],
    "wish": true,
    "titleKr": "7레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 4,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-2.jpg", "/images/front/travel/vis-size/vis-240x190-2.jpg", "/images/front/travel/vis-size/vis-240x190.jpg"],
    "thumbAlt": ["test", "test2", "test3"],
    "wish": true,
    "titleKr": "8레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 3,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-3.jpg"],
    "thumbAlt": ["test"],
    "wish": false,
    "titleKr": "9레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 2,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  },
  {
    "type": "normal",
    "thumbImg": ["/images/front/travel/vis-size/vis-240x190-3.jpg"],
    "thumbAlt": ["test"],
    "wish": false,
    "titleKr": "10레드 루프 인 시애틀 공항 - 씨택",
    "grade": "아주 좋음 4.5",
    "titleEn": "Red Roof Inn Seattle Airport - SEATAC",
    "gradeStar": 2,
    "local": "17, Avenue Kleber, Paris",
    "facilities": "무료와이파이, 무료주차, 다국어지원",
    "badge": ["PRIVIA 특가", "베스트셀러"],
    "price1": 3,
    "price2": 413300,
    "link": "http://www.naver.com"
  }
]
