export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

export const SECTION_MAIN = "SECTION_MAIN";
export const SECTION_EVENT = "SECTION_EVENT";
export const SECTION_GUIDE = "SECTION_GUIDE";

export const SECTION_MYPAGE = "SECTION_MYPAGE";
export const SECTION_MEMBER = "SECTION_MEMBER";
export const SECTION_CUSTOMER = "SECTION_CUSTOMER";

export const SECTION_BUY = "SECTION_BUY";
export const SECTION_SELL = "SECTION_SELL";
export const SECTION_MARKET_PRICE = "SECTION_MARKET_PRICE";
export const SECTION_HOME_SERVICE = "SECTION_HOME_SERVICE";

export const SECTION_AUTO_AUCTION = "SECTION_AUTO_AUCTION";
export const SECTION_PRICING_SYSTEM = "SECTION_PRICING_SYSTEM";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";